import type { NavData } from './'

export const NAV_DATA: NavData[] = [
  {
    Category_id: "reactEcology",
    title: "React生态",
    category_icon: "icon-ui",
    category_item: "reactEcologyItem",
    items: [
      {
        title: "React",
        icon: "https://no.buging.cn/img/react.svg",
        link: "https://zh-hans.reactjs.org/",
        desc: "用于构建用户界面的 JavaScript 库",
      },
      {
        title: "React Router",
        icon: "https://no.buging.cn/img/reactRouter.png",
        link: "https://reactrouter.com/en/main",
        desc: "React Router官方文档",
      },
      {
        title: "Redux",
        icon: "https://no.buging.cn/img/redux.png",
        link: "https://cn.redux.js.org/",
        desc: "Redux官方中文文档",
      },
      {
        title: "Mobx",
        icon: "https://no.buging.cn/img/mobx.jpeg",
        link: "https://zh.mobx.js.org/README.html",
        desc: "Mobx官方中文文档",
      },
      {
        title: "Dvajs",
        icon: "https://no.buging.cn/img/dva.png",
        link: "https://dvajs.com/guide/",
        desc: "Dvajs官方文档",
      },
      {
        title: "Crate-React-App",
        icon: "https://no.buging.cn/img/cra.png",
        link: "https://create-react-app.dev/",
        desc: "React 官方脚手架工具",
      },
      {
        title: "Umi",
        icon: "https://no.buging.cn/img/umi.png",
        link: "https://umijs.org/",
        desc: "企业级前端框架",
      },
      {
        title: "Ant Design",
        icon: "https://no.buging.cn/img/antd.png",
        link: "https://ant.design/index-cn",
        desc: "助力设计开发者「更灵活」地搭建出「更美」的产品，让用户「快乐工作」～",
      },
      {
        title: "Ant Design Pro",
        icon: "https://no.buging.cn/img/antd.png",
        link: "https://pro.ant.design/zh-CN/",
        desc: "开箱即用的中台前端/设计解决方案",
      },
      {
        title: "Pro Components",
        icon: "https://no.buging.cn/img/antd.png",
        link: "https://procomponents.ant.design/",
        desc: "让中后台开发更简单",
      },
      {
        title: "Nextjs",
        icon: "https://no.buging.cn/img/nextjs.png",
        link: "https://nextjs.org/",
        desc: "The React Framework for the Web",
      },
      {
        title: "SWR",
        icon: "https://no.buging.cn/img/swr.png",
        link: "https://swr.vercel.app/zh-CN",
        desc: "用于数据请求的 React Hooks 库",
      },
      {
        title: "React-query",
        icon: "https://no.buging.cn/img/reactQuery.png",
        link: "https://react-query-v3.tanstack.com/",
        desc: "Performant and powerful data synchronization for React",
      },
      {
        title: "umi-request",
        icon: "https://no.buging.cn/img/umi.png",
        link: "https://github.com/umijs/umi-request",
        desc: "网络请求库，基于 fetch 封装, 兼具 fetch 与 axios 的特点, 旨在为开发者提供一个统一的 api 调用方式, 简化使用, 并提供诸如缓存, 超时, 字符编码处理, 错误处理等常用功能.",
      },
      {
        title: "ahooks",
        icon: "https://no.buging.cn/img/ahooks.jpeg",
        link: "https://ahooks.js.org/zh-CN/",
        desc: "一套高质量可靠的 React Hooks 库",
      },
      {
        title: "react-use",
        icon: "https://no.buging.cn/img/react.svg",
        link: "https://github.com/streamich/react-use",
        desc: "有赞团队出品的轻量、可靠的移动端 Vue 组件库",
      },
      {
        title: "Zustand",
        icon: "https://no.buging.cn/img/zustand.png",
        link: "https://youzan.github.io/vant/#/zh-CN/intro",
        desc: "有赞团队出品的轻量、可靠的移动端 Vue 组件库",
      },
      {
        title: "Jotai",
        icon: "https://jotai.org/favicon.svg",
        link: "https://jotai.org/",
        desc: "Primitive and flexible state management for React",
      },
      {
        title: "Valtio",
        icon: "https://no.buging.cn/img/valtio.png",
        link: "https://valtio.pmnd.rs/",
        desc: "Valtio makes proxy-state simple for React and Vanilla",
      },
      {
        title: "Recoil",
        icon: "https://no.buging.cn/img/recoil.png",
        link: "https://recoiljs.org/",
        desc: "A state management library for React",
      },
      {
        title: "Redux Toolkit",
        icon: "https://no.buging.cn/img/reduxToolkit.png",
        link: "https://redux-toolkit.js.org/",
        desc: "The official, opinionated, batteries-included toolset for efficient Redux development",
      },
      {
        title: "Father",
        icon: "https://no.buging.cn/img/umi.png",
        link: "https://github.com/umijs/father",
        desc: "father 是一款 NPM 包研发工具，能够帮助开发者更高效、高质量地研发 NPM 包、生成构建产物、再完成发布。它主要具备以下特性",
      },
      {
        title: "Dumi",
        icon: "https://no.buging.cn/img/dumi.png",
        link: "https://d.umijs.org/",
        desc: "为组件研发而生的静态站点框架",
      },
      {
        title: "Ant Design Mobile",
        icon: "https://no.buging.cn/img/antdm.png",
        link: "https://mobile.ant.design/zh",
        desc: "探索移动端 Web 的体验极限",
      },
      {
        title: "Qiankun",
        icon: "https://no.buging.cn/img/qiankun.png",
        link: "https://qiankun.umijs.org/",
        desc: "可能是你见过最完善的微前端解决方案",
      },
      {
        title: "Motion",
        icon: "https://zos.alipayobjects.com/rmsportal/TOXWfHIUGHvZIyb.svg",
        link: "https://motion.ant.design/index-cn",
        desc: "使用 Ant Motion 能够快速在 React 框架中使用动画。我们提供了单项，组合动画，以及整套解决方案。",
      },
      {
        title: "Remix",
        icon: "https://no.buging.cn/img/remix.png",
        link: "https://remix.run/",
        desc: "Remix is a full stack web framework that lets you focus on the user interface and work back through web standards to deliver a fast, slick, and resilient user experience.",
      },
      {
        title: "飞冰",
        icon: "https://no.buging.cn/img/ice.png",
        link: "https://v3.ice.work/",
        desc: "基于 React 的应用研发框架，开箱即用，同时支持移动端和桌面端",
      },
      {
        title: "Formily",
        icon: "https://no.buging.cn/img/formily.png",
        link: "https://formilyjs.org/zh-CN",
        desc: "阿里巴巴统一前端表单解决方案",
      },
      {
        title: "XRender",
        icon: "https://img.alicdn.com/tfs/TB17UtINiLaK1RjSZFxXXamPFXa-606-643.png",
        link: "https://xrender.fun/",
        desc: "中后台「表单/表格/图表」开箱即用解决方案",
      },
      {
        title: "amis",
        icon: "https://baidu.github.io/amis/static/favicon_b3b0647.png",
        link: "https://baidu.github.io/amis/zh-CN/docs/index",
        desc: "amis 是一个低代码前端框架，它使用 JSON 配置来生成页面，可以减少页面开发工作量，极大提升效率",
      },
      {
        title: "Modernjs",
        icon: "https://lf3-static.bytednsdoc.com/obj/eden-cn/uhbfnupenuhf/favicon.ico",
        link: " https://modernjs.dev/",
        desc: "Modern.js 是字节跳动 Web 工程体系的开源版本，它提供多个解决方案，来帮助开发者解决不同研发场景下的问题。",
      },
    ],
  },
  {
    Category_id: "vueEcology",
    title: "Vue生态",
    category_icon: "icon-vuejs1",
    category_item: "vueEcologyItem",
    items: [
      {
        title: "Vue3",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://cn.vuejs.org/",
        desc: "一套用于构建用户界面的渐进式框架.简单却不失优雅,小巧而不乏大匠",
      },
      {
        title: "Vue2",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://v2.cn.vuejs.org/",
        desc: "一套用于构建用户界面的渐进式框架.简单却不失优雅,小巧而不乏大匠",
      },
      {
        title: "Vue Router",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://router.vuejs.org/zh/",
        desc: "Vue Router官方中文文档",
      },
      {
        title: "Pinia",
        icon: "https://no.buging.cn/img/pinia.png",
        link: "https://pinia.vuejs.org/zh/",
        desc: "符合直觉的Vue.js 状态管理库",
      },
      {
        title: "Vuex",
        icon: "https://no.buging.cn/img/Vuex.png",
        link: "https://vuex.vuejs.org/zh/",
        desc: "Vuex官方中文文档",
      },
      {
        title: "create-vue",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://github.com/vuejs/create-vue",
        desc: "The recommended way to start a Vite-powered Vue project",
      },
      {
        title: "Vue CLI",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://cli.vuejs.org/zh/",
        desc: "Vue.js 官方脚手架工具",
      },
      {
        title: "awesome-vue",
        icon: "https://no.buging.cn/img/awesome-vue.png",
        link: "https://github.com/vuejs/awesome-vue",
        desc: "(vue资源汇总)与Vue.js相关的精彩内容和精选列表",
      },
      {
        title: "awesome-github-vue",
        icon: "https://no.buging.cn/img/awesome-github-vue.png",
        link: "https://github.com/opendigg/awesome-github-vue",
        desc: "Vue相关开源项目库汇总(中文)",
      },
      {
        title: "Element Plus",
        icon: "https://element-plus.org/images/element-plus-logo-small.svg",
        link: "https://element-plus.org/zh-CN/#/zh-CN",
        desc: "基于 Vue 3，面向设计师和开发者的组件库",
      },
      {
        title: "ElementUI",
        icon: "https://no.buging.cn/img/element.png",
        link: "https://element.eleme.cn/#/zh-CN",
        desc: "Element，一套为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库",
      },
      {
        title: "Ant Design Vue",
        icon: "https://no.buging.cn/img/ant-design-vue.png",
        link: "https://vue.ant.design/docs/vue/introduce-cn/",
        desc: "Ant Design 的 Vue 实现，开发和服务于企业级后台产品。",
      },
      {
        title: "Vant",
        icon: "https://no.buging.cn/img/vant.png",
        link: "https://youzan.github.io/vant/#/zh-CN/intro",
        desc: "有赞团队出品的轻量、可靠的移动端 Vue 组件库",
      },
      {
        title: "cube-ui",
        icon: "https://no.buging.cn/img/cube-ui.png",
        link: "https://didi.github.io/cube-ui/#/zh-CN",
        desc: "滴滴团队基于 Vue.js 实现的精致移动端组件库",
      },
      {
        title: "mint-ui",
        icon: "https://no.buging.cn/img/mint-ui.png",
        link: "http://mint-ui.github.io/#!/zh-cn",
        desc: "饿了么团队出品的基于 Vue.js 的移动端组件库",
      },
      {
        title: "Vux",
        icon: "https://no.buging.cn/img/vux.png",
        link: "https://vux.li/#/zh-CN/README",
        desc: "一个凑合的 Vue.js 移动端 UI 组件库",
      },
      {
        title: "Vuetifyjs",
        icon: "https://no.buging.cn/img/vuetifyjs.png",
        link: "https://vuetifyjs.com/zh-Hans/",
        desc: "一个高品质综合实用性、体验、格调的框架",
      },
      {
        title: "Quasar",
        icon: "https://no.buging.cn/img/Quasar.png",
        link: "https://quasar-framework.org/",
        desc: "较成熟的组件库，大名鼎鼎，组件丰富到变态~",
      },
      {
        title: "Vuesax",
        icon: "https://no.buging.cn/img/vuesax.png",
        link: "https://lusaxweb.github.io/vuesax/#/",
        desc: "有若干常用组件，但有着非常美妙的色彩和反馈效果，充满活力与灵气",
      },
      {
        title: "Eagle.js",
        icon: "https://no.buging.cn/img/eaglejs.png",
        link: "https://github.com/Zulko/eagle.js",
        desc: "一个使用 Vue.js 开发的幻灯片框架",
      },
      {
        title: "Vue-grid-layout",
        icon: "https://no.buging.cn/img/vue-grid-layout.png",
        link: "https://github.com/jbaysolutions/vue-grid-layout",
        desc: "Vue.js 可拖动且可调整大小的网格布局",
      },
      {
        title: "vue-content-loader",
        icon: "https://no.buging.cn/img/vue-content-loader.png",
        link: "https://github.com/egoist/vue-content-loader",
        desc: "用于创建占位符加载的 SVG 组件，例如 Facebook 卡片加载",
      },
      {
        title: "vue-virtual-scroller",
        icon: "https://no.buging.cn/img/vue-virtual-scroller.png",
        link: "https://github.com/Akryum/vue-virtual-scroller",
        desc: "可以平滑滚动任意数量的数据",
      },
      {
        title: "Mand Mobile",
        icon: "https://no.buging.cn/img/mand-mobile.png",
        link: "https://mand-mobile.github.io/",
        desc: "面向金融场景的Vue移动端UI组件库",
      },
      {
        title: "Vue-Access-Control",
        icon: "https://no.buging.cn/img/vueac.png",
        link: "https://github.com/tower1229/Vue-Access-Control",
        desc: "一套基于Vue/Vue-Router/axios 实现的前端用户权限控制解决方案",
      },
      {
        title: "Vue-Tree-Chart",
        icon: "https://no.buging.cn/img/vuetc.png",
        link: "https://github.com/tower1229/Vue-Tree-Chart",
        desc: "基于Vue2的树形图组件",
      },
      {
        title: "vue-meta-info",
        icon: "https://no.buging.cn/img/vue_meta_info.png",
        link: "https://github.com/muwoo/vue-meta-info",
        desc: "vue-meta-info是一个基于vue 2.0的插件，它会让你更好的管理你的app里面的meta信息设置vue，支持SSR",
      },
      {
        title: "vue-simple-uploader",
        icon: "https://no.buging.cn/img/vue_simple_uploader.png",
        link: "https://github.com/simple-uploader/vue-uploader/blob/master/README_zh-CN.md",
        desc: "一个基于 simple-uploader.js 的 Vue 上传组件",
      },
      {
        title: "NutUI",
        icon: "https://no.buging.cn/img/nutui.png",
        link: "http://nutui.jd.com",
        desc: "一套京东风格的轻量级移动端Vue组件库",
      },
    ],
  },
  {
    Category_id: "nodejs",
    title: "Node相关",
    category_icon: "icon-js",
    category_item: "nodejsItem",
    items: [
      {
        title: "nodejs文档",
        icon: "https://no.buging.cn/img/nodeapp.png",
        link: "http://nodejs.cn/",
        desc: "Node.js 是一个开源的、跨平台的 JavaScript 运行时环境。",
      },
      {
        title: "Eggjs",
        icon: "https://www.eggjs.org/logo.svg",
        link: "https://www.eggjs.org/zh-CN",
        desc: "为企业级框架和应用而生",
      },
      {
        title: "Express",
        icon: "https://no.buging.cn/img/express.png",
        link: "https://www.expressjs.com.cn/",
        desc: "基于 Node.js 平台，快速、开放、极简的 Web 开发框架",
      },
      {
        title: "Koa",
        icon: "https://no.buging.cn/img/koa.png",
        link: "https://koa.bootcss.com/",
        desc: "基于node平台的下一代web开发框架",
      },
      {
        title: "Nest",
        icon: "https://no.buging.cn/img/nest.png",
        link: "https://docs.nestjs.cn/",
        desc: "用于构建高效且可伸缩的服务端应用程序的渐进式 Node.js 框架。",
      },
      {
        title: "midway",
        icon: "https://no.buging.cn/img/midway.png",
        link: "https://midwayjs.org/",
        desc: "Midway 是阿里巴巴 - 淘宝前端架构团队，基于渐进式理念研发的 Node.js 框架，通过自研的依赖注入容器，搭配各种上层模块，组合出适用于不同场景的解决方案",
      },
      {
        title: "Strapi",
        icon: "https://strapi.io/assets/favicon-32x32.png",
        link: " https://strapi.io/",
        desc: "Strapi is the leading open-source headless CMS. It’s 100% JavaScript and fully customizable.",
      },
      {
        title: "Hapi",
        icon: "https://hapi.dev/favicon.png?v=1.0",
        link: "https://hapi.dev/tutorials/?lang=zh_CN",
        desc: "Build powerful, scalable applications, with minimal overhead and full out-of-the-box functionality - your code, your way",
      },
      {
        title: "Joi",
        icon: "https://joi.dev/favicon2.png?v=1.0",
        link: "https://joi.dev/api/",
        desc: "The most powerful schema description language and data validator for JavaScript",
      },
    ],
  },
  {
    Category_id: "miniProgram",
    title: "小程序相关",
    category_icon: "icon-xiaochengxu1",
    category_item: "miniProgramItem",
    items: [
      {
        title: "微信小程序文档",
        icon: "https://no.buging.cn/img/weixin.png",
        link: "https://developers.weixin.qq.com/miniprogram/dev/index.html",
        desc: "微信小程序官方开发者文档",
      },
      {
        title: "微信开发者社区",
        icon: "https://no.buging.cn/img/developersweixin.png",
        link: "https://developers.weixin.qq.com/community/develop/question",
        desc: "小程序开发者专区，微信公众平台,微信开放社区,开发者专区",
      },
      {
        title: "微信开放平台",
        icon: "https://no.buging.cn/img/developersweixin.png",
        link: "https://open.weixin.qq.com/",
        desc: "微信开放平台",
      },
      {
        title: "微信小程序开发资源汇总",
        icon: "https://no.buging.cn/img/weixin.png",
        link: "https://github.com/justjavac/awesome-wechat-weapp",
        desc: "微信小程序开发资源汇总",
      },
      {
        title: "WePY",
        icon: "https://no.buging.cn/img/wepy.png",
        link: "https://wepyjs.github.io/wepy-docs/",
        desc: "支持组件化的小程序开发框架",
      },
      {
        title: "mpvue",
        icon: "https://no.buging.cn/img/mpvue.png",
        link: "http://mpvue.com/",
        desc: "基于 Vue.js 的小程序开发框架，从底层支持 Vue.js 语法和构建工具体系",
      },
      {
        title: "uni-app",
        icon: "https://no.buging.cn/img/uniapp.png",
        link: "https://uniapp.dcloud.io/",
        desc: "uni-app 是一个使用 Vue.js 开发所有前端应用的框架，开发者编写一套代码，可编译到iOS、Android、H5、以及各种小程序等多个平台。",
      },
      {
        title: "WeUI",
        icon: "https://no.buging.cn/img/weui.png",
        link: "https://github.com/Tencent/weui",
        desc: "一套同微信原生视觉体验一致的基础样式库 为微信 Web 开发量身设计，令用户的使用感知更加统一",
      },
      {
        title: "Taro",
        icon: "https://no.buging.cn/img/taro.png",
        link: "https://taro.js.org/",
        desc: "使用 React 的方式开发小程序的框架，同时支持生成多端应用",
      },
      {
        title: "Chameleon",
        icon: "https://no.buging.cn/img/cmljs.png",
        link: "https://cml.js.org/",
        desc: "一套代码运行多端，一端所见即多端所见",
      },
      {
        title: "iconfont-cli",
        icon: "https://img.alicdn.com/imgextra/i4/O1CN01Z5paLz1O0zuCC7osS_!!6000000001644-55-tps-83-82.svg",
        link: "https://github.com/iconfont-cli",
        desc: "多色彩iconfont图标解决方案",
      },
      {
        title: "natapp",
        icon: "https://cdn.natapp.cn/assets/natapp/img/logo.png?version=20220415",
        link: "https://natapp.cn/",
        desc: "natapp是基于ngrok的国内高速内网穿透专业服务商,独家彻底解决ngrok1.7内存泄漏问题.稳定拒绝掉线,适用于微信开发调试,本地架设演示服务器,",
      },
    ],
  },
  {
    Category_id: "UIFrame",
    title: "UI框架",
    category_icon: "icon-ui",
    category_item: "UIFrameItem",
    items: [
      {
        title: "Ant Design",
        icon: "https://no.buging.cn/img/antdesign.png",
        link: "https://ant.design/index-cn",
        desc: "蚂蚁金服的开箱即用的中台前端/设计解决方案",
      },
      {
        title: "Element Plus",
        icon: "https://element-plus.org/images/element-plus-logo-small.svg",
        link: "https://element-plus.org/zh-CN/#/zh-CN",
        desc: "基于 Vue 3，面向设计师和开发者的组件库",
      },
      {
        title: "ElementUI",
        icon: "https://no.buging.cn/img/element.png",
        link: "https://element.eleme.cn/#/zh-CN",
        desc: "Element，一套为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库",
      },
      {
        title: "Ant Design Vue",
        icon: "https://no.buging.cn/img/ant-design-vue.png",
        link: "https://vue.ant.design/docs/vue/introduce-cn/",
        desc: "Ant Design 的 Vue 实现，开发和服务于企业级后台产品。",
      },
      {
        title: "iView",
        icon: "https://no.buging.cn/img/iview.png",
        link: "https://www.iviewui.com/",
        desc: "一套基于 Vue.js 的高质量 UI 组件库",
      },
      {
        title: "Tailwind CSS",
        icon: "https://tailwindcss.com/favicons/favicon.ico?v=3 ",
        link: "https://tailwindcss.com/",
        desc: "Tailwind CSS 是一个功能类优先的 CSS 框架",
      },
      {
        title: "Bootstrap",
        icon: "https://no.buging.cn/img/bootcss.jpg",
        link: "http://www.bootcss.com/",
        desc: "简洁、直观、强悍的前端开发框架，让web开发更迅速、简单。",
      },
      {
        title: "Foundation",
        icon: "https://no.buging.cn/img/foundation.png",
        link: "https://foundation.zurb.com/",
        desc: "一个易用、强大而且灵活的框架,用于构建基于任何设备上的 Web 应用。",
      },
      {
        title: "Pure.css",
        icon: "https://no.buging.cn/img/purecss.png",
        link: "https://purecss.io/",
        desc: "雅虎公司出品的一组轻量级、响应式纯css模块,适用于任何Web项目",
      },
      {
        title: "Semantic UI",
        icon: "https://no.buging.cn/img/semanticui.png",
        link: "https://semantic-ui.com/",
        desc: "一个用来帮助设计出漂亮的、响应化、人性化的网络框架",
      },
      {
        title: "Material UI",
        icon: "https://no.buging.cn/img/material-ui.png",
        link: "https://material-ui.com/",
        desc: "一组反应元件，实现谷歌的材料设计",
      },
      {
        title: "MetroUI",
        icon: "https://no.buging.cn/img/metroui.png",
        link: "https://metroui.org.ua/",
        desc: "好看好用，重点是样式特别、个性",
      },
      {
        title: "QMUI Web",
        icon: "https://no.buging.cn/img/QMUIWeb.png",
        link: "https://qmuiteam.com/web/page/index.html",
        desc: "腾讯旗下团队 web UI解决方案",
      },
      {
        title: "MDUI",
        icon: "https://no.buging.cn/img/mdui.png",
        link: "https://www.mdui.org/",
        desc: "MDUI 是一套用于开发 Material Design 网页的前端框架",
      },
      {
        title: "Mobi.css",
        icon: "https://no.buging.cn/img/mobicss.png",
        link: "http://getmobicss.com/",
        desc: "轻量灵活的移动端 CSS 框架",
      },
      {
        title: "PaperCSS",
        icon: "https://no.buging.cn/img/getpapercss.png",
        link: "https://www.getpapercss.com/",
        desc: "一个不太常规的CSS框架，如果你希望你的网站有手绘风格感觉，选择它准没错。",
      },
    ],
  },
  {
    Category_id: "buildTools",
    title: "编译&构建&打包",
    category_icon: "icon-goujian",
    category_item: "buildToolsItem",
    items: [
      {
        title: "Webpack",
        icon: "https://no.buging.cn/img/Webpack.png",
        link: "https://www.webpackjs.com/",
        desc: "目前最热门的前端资源模块化管理和打包工具",
      },
      {
        title: "Vite",
        icon: "https://no.buging.cn/img/vite.png",
        link: "https://cn.vitejs.dev/",
        desc: "下一代的前端工具链，为开发提供极速响应",
      },
      {
        title: "Rollup",
        icon: "https://no.buging.cn/img/rollup.png",
        link: "https://www.rollupjs.com/",
        desc: "Rollup 是一个 JavaScript 模块打包工具，可以将多个小的代码片段编译为完整的库和应用",
      },
      {
        title: "SWC",
        icon: "https://swc.rs/favicon/favicon-32x32.png",
        link: "https://swc.rs/",
        desc: "SWC is an extensible Rust-based platform for the next generation of fast developer tools. It's used by tools like Next.js",
      },
      {
        title: "Esbuild",
        icon: "https://no.buging.cn/img/esbuild.png",
        link: "https://esbuild.github.io/",
        desc: "An extremely fast bundler for the web",
      },
      {
        title: "Turbopack",
        icon: "https://no.buging.cn/img/turbopack.jpeg",
        link: "https://turbo.build/",
        desc: "Turbo is an incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust",
      },
      {
        title: "Gulp",
        icon: "https://no.buging.cn/img/Gulp.png",
        link: "https://www.gulpjs.com.cn/",
        desc: "用自动化构建工具增强你的工作流程！",
      },
      {
        title: "Grunt",
        icon: "https://no.buging.cn/img/Grunt.png",
        link: "https://www.gruntjs.net/",
        desc: "JavaScript 世界的构建工具",
      },
      {
        title: "Babel",
        icon: "https://no.buging.cn/img/babel.png",
        link: "https://www.babeljs.cn/",
        desc: "Babel 是一个 JavaScript 编译器。",
      },
      {
        title: "Pnpm",
        icon: "https://no.buging.cn/img/pnpm.png",
        link: "https://pnpm.io/zh/",
        desc: "通过 npm 可以安装、共享、分发代码,管理项目依赖关系。",
      },
      {
        title: "Lerna",
        icon: "https://lerna.js.org/images/lerna-logo-light.svg",
        link: "https://lerna.js.org/",
        desc: "Lerna is a fast, modern build system for managing and publishing multiple JavaScript/TypeScript packages from the same repository.",
      },
      {
        title: "Npm",
        icon: "https://no.buging.cn/img/npmjs.png",
        link: "https://www.npmjs.com/",
        desc: "通过 npm 可以安装、共享、分发代码,管理项目依赖关系。",
      },
      {
        title: "Yarn",
        icon: "https://yarnpkg.com/favicon-32x32.png?v=775b53071ebde4f6d738805a2d9fcb72",
        link: "https://yarnpkg.com/",
        desc: "快速、可靠、安全的依赖管理。",
      },
      {
        title: "PostCSS",
        icon: "https://no.buging.cn/img/postcss.png",
        link: "https://www.postcss.com.cn/",
        desc: "是一个用 JavaScript 工具和插件转换 CSS 代码的工具",
      },
      {
        title: "Parcel",
        icon: "https://no.buging.cn/img/parceljs.png",
        link: "https://parceljs.org/",
        desc: "极速零配置Web应用打包工具",
      },
      {
        title: "PWA Universal Builder",
        icon: "https://no.buging.cn/img/pwa.png",
        link: "https://pwa.cafe/",
        desc: "一款脚手架构建工具，方便创建基于Preact，React，Vue和Svelte的项目，开箱及支持Babel，Bublé，Browserlist，TypeScript，PostCSS，ESLint，Prettier和Service Workers！",
      },
      {
        title: "Husky",
        icon: "https://no.buging.cn/img/husky.svg",
        link: "https://github.com/typicode/husky",
        desc: "You can use it to lint your commit messages, run tests, lint code, etc... when you commit or push. Husky supports all Git hooks.",
      },
      {
        title: "Plop",
        icon: "https://plopjs.com/favicon-32x32.png",
        link: "https://plopjs.com/",
        desc: "Plop is a little tool that saves you time and helps your team build new files with consistency",
      },
      {
        title: "Bun",
        icon: "https://bun.sh/logo-square.jpg",
        link: "https://bun.sh/",
        desc: "Bun is a fast all-in-one JavaScript runtime",
      },
      {
        title: "Bower",
        icon: "https://no.buging.cn/img/bower.png",
        link: "https://bower.io/",
        desc: "bower是一种包管理器,它可用于搜索、安装和卸载如JavaScript、HTML、CSS之类的网络资源。",
      },
      {
        title: "Critters",
        icon: "https://no.buging.cn/img/critters.png",
        link: "https://github.com/GoogleChromeLabs/critters",
        desc: "webpack的插件，它可以很方便的配置内联关键css( critical CSS ),其余的css部分则会异步加载，由于它不使用无头浏览器(headless browser)呈现内容，因此快速轻巧。",
      },
    ],
  },
  {
    Category_id: "framework",
    title: "框架类库",
    category_icon: "icon-iframetianjia",
    category_item: "frameworkItem",
    items: [
      {
        title: "Single Spa",
        icon: "https://single-spa.js.org/img/single-spa-mark-magenta.svg",
        link: "https://single-spa.js.org/",
        desc: "A javascript router for front-end microservices",
      },
      {
        title: "Qiankun",
        icon: "https://gw.alipayobjects.com/zos/bmw-prod/8a74c1d3-16f3-4719-be63-15e467a68a24/km0cv8vn_w500_h500.png",
        link: "https://qiankun.umijs.org/zh",
        desc: "可能是你见过最完善的微前端解决方案",
      },
      {
        title: "无界",
        icon: "https://wujie-micro.github.io/doc/wujie.svg",
        link: "https://wujie-micro.github.io/doc/",
        desc: "极致的微前端框架,基于 WebComponent 容器 + iframe 沙箱",
      },
      {
        title: "MicroApp",
        icon: "https://zeroing.jd.com/micro-app/home/assets/logo.png",
        link: "https://zeroing.jd.com/micro-app/",
        desc: "一款轻量、高效、功能强大的微前端框架",
      },
      {
        title: "Garfish",
        icon: "https://lf3-static.bytednsdoc.com/obj/eden-cn/dhozeh7vhpebvog/open-garfish/icons/icon.png",
        link: "https://www.garfishjs.org/",
        desc: "包含构建微前端系统时所需要的基本能力，任意前端框架均可使用。接入简单，可轻松将多个前端应用组合成内聚的单个产品",
      },
      {
        title: "EMP",
        icon: "https://emp2.netlify.app/favicon.ico",
        link: " https://emp2.netlify.app/",
        desc: "下一代微前端构建方案，聚焦 ESM 微前端生态闭环建设",
      },
      {
        title: "ICESTARK",
        icon: "https://micro-frontends.ice.work/img/logo.png",
        link: "https://micro-frontends.ice.work/",
        desc: "面向大型系统的微前端解决方案",
      },
      {
        title: "Lowcode Engine",
        icon: "https://img.alicdn.com/imgextra/i2/O1CN01TNJDDg20pKniPOkN4_!!6000000006898-2-tps-66-78.png",
        link: "https://lowcode-engine.cn/index",
        desc: "基于 Low-Code Engine 快速打造高生产力的低代码研发平台",
      },
      {
        title: "GoView",
        icon: "https://www.mtruning.club/logo.svg",
        link: "https://www.mtruning.club/",
        desc: "低代码数据可视化,开源、精美、便捷、规范、交互自然",
      },
      {
        title: "tmagic-editor",
        icon: "https://tencent.github.io/tmagic-editor/docs/favicon.png",
        link: "https://tencent.github.io/tmagic-editor/docs/guide/introduction.html",
        desc: "tmagic-editor可视化开源项目是从魔方平台演化而来的开源项目，意在提供一个供开发者快速搭建可视化搭建平台的解决方案。",
      },
      {
        title: "Puppeteer",
        icon: "https://pptr.dev/img/favicon.ico",
        link: "https://pptr.dev/",
        desc: "Puppeteer is a Node.js library which provides a high-level API to control Chrome/Chromium over the DevTools Protocol. Puppeteer runs in headless mode by default, but can be configured to run in full (non-headless) Chrome/Chromium.",
      },
      {
        title: "Vue",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://cn.vuejs.org/",
        desc: "一套用于构建用户界面的渐进式框架.简单却不失优雅,小巧而不乏大匠",
      },
      {
        title: "React",
        icon: "https://no.buging.cn/img/reactdocschina.jpg",
        link: "https://react.docschina.org/",
        desc: "React是一个JavaScript框架,用于构建“可预期的”和“声明式的”Web用户界面.",
      },
      {
        title: "Preact",
        icon: "https://no.buging.cn/img/preact.png",
        link: "https://preactjs.com/",
        desc: "一个快速轻量的 React 替代方案，具有 ES6 API、组件化和虚拟 DOM",
      },
      {
        title: "Egg",
        icon: "https://www.eggjs.org/logo.svg",
        link: "https://eggjs.org/zh-cn/",
        desc: "一个用于更好地构建企业应用的框架，内置流程管理，高度可定制，有强大的插件系统。",
      },
      {
        title: "Angular",
        icon: "https://no.buging.cn/img/angular.png",
        link: "https://www.angular.cn/",
        desc: "一套框架，多种平台移动端 & 桌面端",
      },
      {
        title: "AngularJs",
        icon: "https://no.buging.cn/img/angularjs.jpg",
        link: "http://www.angularjs.net.cn/",
        desc: "Google推出的MVVM框架",
      },
      {
        title: "Flutter",
        icon: "https://no.buging.cn/img/flutter.png",
        link: "https://flutter.io/",
        desc: "Flutter是谷歌的移动UI框架，可以快速在iOS和Android上构建高质量的原生用户界面。",
      },
      {
        title: "Electron",
        icon: "https://www.electronjs.org/zh/assets/img/logo.svg",
        link: "https://www.electronjs.org/zh/",
        desc: "Build cross-platform desktop apps with JavaScript, HTML, and CSS",
      },
      {
        title: "Tauri",
        icon: "https://tauri.app/zh-cn/meta/favicon-96x96.png",
        link: "https://tauri.app/zh-cn/",
        desc: "Build faster websites",
      },
      {
        title: "React Native",
        icon: "https://reactnative.dev/img/favicon.ico",
        link: "https://reactnative.dev/",
        desc: "Build faster websites",
      },
      {
        title: "JQuery",
        icon: "https://no.buging.cn/img/jquery.png",
        link: "http://jquery.com/",
        desc: "jQuery是一个快速、简洁的JavaScript框架.",
      },
      {
        title: "Zepto",
        icon: "https://no.buging.cn/img/Zepto.jpg",
        link: "https://github.com/madrobby/zepto",
        desc: "Zepto最初是为移动端开发的库,是jQuery的轻量级替代品",
      },
      {
        title: "Backbone",
        icon: "https://no.buging.cn/img/backbone.jpg",
        link: "https://github.com/jashkenas/backbone",
        desc: "一套web开发框架,基于jQuery和underscore的一个前端js框架。",
      },
      {
        title: "Ember.js",
        icon: "https://no.buging.cn/img/ember.jpg",
        link: "https://www.emberjs.com/",
        desc: "一个用于创建 web 应用的 JavaScript MVC 框架",
      },
      {
        title: "KISSY",
        icon: "https://no.buging.cn/img/kissy.png",
        link: "http://docs.kissyui.com/",
        desc: "KISSY 是一款跨终端、模块化、高性能、使用简单的 JavaScript 框架。",
      },
      {
        title: "RequireJS",
        icon: "https://no.buging.cn/img/requirejs.png",
        link: "http://www.requirejs.cn/",
        desc: "RequireJS是一个非常小巧的JavaScript模块载入框架,是AMD规范最好的实现者之一",
      },
      {
        title: "Sea.js",
        icon: "https://no.buging.cn/img/seajs.png",
        link: "https://seajs.github.io/seajs/docs/",
        desc: "SeaJS是一个遵循CMD规范的JavaScript模块加载框架",
      },
      {
        title: "Astro",
        icon: "https://astro.build/assets/press/logomark-light.svg",
        link: "https://astro.build/",
        desc: "Build faster websites",
      },
      {
        title: "flv.js",
        icon: "https://www.bilibili.com/favicon.ico?v=1",
        link: " https://github.com/Bilibili/flv.js/",
        desc: "blibli出品的视频播放器",
      },
      {
        title: "fabricjs",
        icon: "http://fabricjs.com/favicon.ico",
        link: " http://fabricjs.com/",
        desc: "canvas库",
      },
      {
        title: "Verdaccio",
        icon: "https://verdaccio.org/img/logo/uk/verdaccio-tiny-uk-no-bg.svg",
        link: "https://verdaccio.org/",
        desc: "A lightweight Node.js private proxy registry",
      },
    ],
  },
  {
    Category_id: "JavaScriptAbout",
    title: "JavaScript相关",
    category_icon: "icon-js",
    category_item: "JavaScriptAboutItem",
    items: [
      {
        title: "JavaScript开发者应懂的33个概念",
        icon: "https://no.buging.cn/img/33_js_concepts.png",
        link: "https://github.com/stephentian/33-js-concepts/blob/master/README.md",
        desc: "这个项目是为了帮助开发者掌握 JavaScript 概念而创立的。它不是必备，但在未来学习（JavaScript）中，可以作为一篇指南。",
      },
      {
        title: "JavaScript 秘密花园",
        icon: "https://no.buging.cn/img/JavaScript-Garden.png",
        link: "http://bonsaiden.github.io/JavaScript-Garden/zh/",
        desc: "JavaScript 细节点分析",
      },
      {
        title: "ECMAScript 6 入门",
        icon: "https://no.buging.cn/img/es6.png",
        link: "http://es6.ruanyifeng.com/#README",
        desc: "阮一峰的《ECMAScript 6入门》",
      },
      {
        title: "30 seconds of code",
        icon: "https://no.buging.cn/img/30secondsofcode.png",
        link: "https://30secondsofcode.org/",
        desc: "分享了大量有用的Javascript片段,你可以在30秒或更少时间中理解。",
      },
      {
        title: "JS 函数式编程指南",
        icon: "https://no.buging.cn/img/dianzishu.png",
        link: "https://llh911001.gitbooks.io/mostly-adequate-guide-chinese/content/",
        desc: "JS 函数式编程指南 gitbook电子书",
      },
      {
        title: "TypeScript中文网",
        icon: "https://no.buging.cn/img/TypeScriptcn.png",
        link: "https://www.tslang.cn/",
        desc: "TypeScript中文网中文文档",
      },
      {
        title: "TypeScript Handbook",
        icon: "https://no.buging.cn/img/dianzishu.png",
        link: "https://zhongsp.gitbooks.io/typescript-handbook/content/",
        desc: "TypeScript Handbook（中文版）",
      },
    ],
  },
  {
    Category_id: "cssAbout",
    title: "CSS相关",
    category_icon: "icon-socialcss3outline",
    category_item: "cssAboutItem",
    items: [
      {
        title: "Sass",
        icon: "https://no.buging.cn/img/sasscss.jpg",
        link: "http://sass.bootcss.com/",
        desc: "Sass 是成熟、稳定、强大的 CSS 扩展语言。",
      },
      {
        title: "Less",
        icon: "https://no.buging.cn/img/lesscss.png",
        link: "https://less.bootcss.com/",
        desc: "给 CSS 加点料,是一门向后兼容的 CSS 扩展语言。",
      },
      {
        title: "Stylus",
        icon: "https://no.buging.cn/img/stylus.png",
        link: "http://stylus-lang.com/",
        desc: "富有表现力的、动态的、健壮的CSS",
      },
      {
        title: "Animate.css",
        icon: "https://no.buging.cn/img/animatecss.jpg",
        link: "https://daneden.github.io/animate.css/",
        desc: "css内置了很多典型的css3动画,兼容性好使用方便。",
      },
      {
        title: "CSS 选择器演示",
        icon: "https://no.buging.cn/img/css_selecter.png",
        link: "https://www.haorooms.com/tools/css_selecter/",
        desc: "本css选择器可以通过本页面直观的理解 CSS 选择器的作用区域",
      },
      {
        title: "浏览器hack大全",
        icon: "https://no.buging.cn/img/browserhacks.png",
        link: "http://browserhacks.com/",
        desc: "由于不同的浏览器，对CSS的解析认识不一样，因此会导致生成的页面效果不一样，于是就有了针对不同的浏览器写不同的CSS code，这就叫CSS hack",
      },
      {
        title: "CSS Hack Table",
        icon: "https://no.buging.cn/img/swordaircsstools.png",
        link: "https://swordair.com/tools/css-hack-table/",
        desc: "CSS hack 表格",
      },
      {
        title: "LoadersCSS",
        icon: "https://no.buging.cn/img/loaders.png",
        link: "https://connoratherton.com/loaders",
        desc: "用 CSS 技术实现 loading 动画",
      },
      {
        title: "text-spinners",
        icon: "https://no.buging.cn/img/text-spinners.png",
        link: "https://github.com/maxbeier/text-spinners",
        desc: "又是一款 spinners 效果的库，用来做 loading 正合适。",
      },
      {
        title: "Can I Use",
        icon: "https://no.buging.cn/img/caniuse.png",
        link: "https://caniuse.com/",
        desc: "一个检测浏览器对JS、HTML5、CSS、SVG或者其他Web前端相关特性支持程度的列表。",
      },
      {
        title: "A Single Div",
        icon: "https://no.buging.cn/img/asinglediv.png",
        link: "https://a.singlediv.com/",
        desc: "纯CSS实现的div图片盒子,很有意思",
      },
      {
        title: "30 Seconds of CSS",
        icon: "https://no.buging.cn/img/30-seconds-of-css.png",
        link: "https://30-seconds.github.io/30-seconds-of-css/",
        desc: "收集了常用的CSS代码段,你可以通过30秒或者更少的时间去了解它",
      },
      {
        title: "CSS Inspiration -- CSS灵感",
        icon: "https://no.buging.cn/img/CSS-Inspiration.png",
        link: "https://chokcoco.github.io/CSS-Inspiration/#/",
        desc: "学习 CSS 的灵感，以分类的形式，展示不同 CSS 属性或者不同的课题使用 CSS 来解决的各种方法。",
      },
      {
        title: "CSScomb",
        icon: "https://no.buging.cn/img/csscomb.png",
        link: "http://csscomb.com/",
        desc: "一个超棒的CSS属性排序工具",
      },
      {
        title: "Button Generator",
        icon: "https://no.buging.cn/img/ButtonGenerator.png",
        link: "https://www.bestcssbuttongenerator.com/",
        desc: "提供各种按钮的CSS代码，你可以从预设的按钮中选择并使用模板用于自己的设计",
      },
      {
        title: "EnjoyCSS",
        icon: "https://no.buging.cn/img/enjoycss.png",
        link: "https://enjoycss.com/",
        desc: "一个完整的代码生成器，可以自定义输入域或CSS3按钮",
      },
      {
        title: "Animista",
        icon: "https://no.buging.cn/img/animista.png",
        link: "http://animista.net/",
        desc: "CSS动态效果样式在线自定义",
      },
      {
        title: "AniCollection",
        icon: "https://no.buging.cn/img/anicollection.png",
        link: "http://anicollection.github.io/#/",
        desc: "CSS3动效预设收藏集合",
      },
      {
        title: "CSS Generator Tool",
        icon: "https://no.buging.cn/img/cssgenerator.png",
        link: "https://cssgenerator.org/",
        desc: "CSS各种对象样式和效果在线生成工具",
      },
      {
        title: "Ceaser",
        icon: "https://no.buging.cn/img/ceaser.png",
        link: "https://matthewlein.com/tools/ceaser",
        desc: "CSS贝塞尔动画在线调试工具",
      },
      {
        title: "CSS Gradient Generator",
        icon: "https://no.buging.cn/img/gradient-editor.png",
        link: "http://www.colorzilla.com/gradient-editor/",
        desc: "CSS渐变在线生成器",
      },
      {
        title: "CSS Reference",
        icon: "https://no.buging.cn/img/cssreference.png",
        link: "https://cssreference.io/",
        desc: "非常棒的免费的CSS属性指导手册",
      },
      {
        title: "ColorSpark",
        icon: "https://no.buging.cn/img/colorspark.png",
        link: "https://colorspark.app/",
        desc: "随机生成好看的颜色、渐变色，可以一键复制 CSS 代码",
      },
      {
        title: "FontSpark",
        icon: "https://no.buging.cn/img/fontspark.png",
        link: "https://fontspark.app/",
        desc: "随机字体在线预览，用过都说好。",
      },
      {
        title: "Pixel Art to CSS",
        icon: "https://no.buging.cn/img/pixelartcss.png",
        link: "https://github.com/jvalen/pixel-art-react",
        desc: "由React提供的像素艺术动画和绘图Web应用程序",
      },
      {
        title: "Autoprefixer CSS",
        icon: "https://no.buging.cn/img/autoprefixer.png",
        link: "http://autoprefixer.github.io/",
        desc: "(在线)autoprefixer是一个postcss插件，用于解析CSS并添加供应商前缀。",
      },
    ],
  },
  {
    Category_id: "graphical",
    title: "可视化",
    category_icon: "icon-tubiao",
    category_item: "graphicalItem",
    items: [
      {
        title: "D3.js",
        icon: "https://no.buging.cn/img/d3js.png",
        link: "https://d3js.org/",
        desc: "用动态图形显示数据的JavaScript库",
      },
      {
        title: "Echarts",
        icon: "https://no.buging.cn/img/echarts.png",
        link: "http://echarts.baidu.com/",
        desc: "百度开发的可定制的数据可视化图表",
      },
      {
        title: "bizcharts",
        icon: "https://gw.alicdn.com/tfs/TB1_W9oE.T1gK0jSZFrXXcNCXXa-116-92.png",
        link: "https://bizcharts.taobao.com/",
        desc: "企业中后台的，可视化解决方案",
      },
      {
        title: "three.js",
        icon: "https://no.buging.cn/img/threejs.png",
        link: "https://threejs.org/",
        desc: "three.js是JavaScript编写的WebGL第三方库。提供了非常多的3D显示功能",
      },
      {
        title: "Babylon.js",
        icon: "https://no.buging.cn/img/babylon.png",
        link: "https://www.babylonjs.com/",
        desc: "我们的使命是创建世界上最强大、最惊艳、最易用的Web3D渲染引擎，并且我们坚持让它完全开源和免费",
      },
      {
        title: "AntV",
        icon: "https://no.buging.cn/img/antv.png",
        link: "https://antv.alipay.com/",
        desc: "蚂蚁金服全新一代数据可视化解决方案，致力于提供一套简单方便、专业可靠、无限可能的数据可视化最佳实践。",
      },
      {
        title: "Ant Design Charts",
        icon: "https://gw.alipayobjects.com/zos/antfincdn/FLrTNDvlna/antv.png",
        link: "https://charts.ant.design/zh",
        desc: "简单好用的 React 图表库",
      },
      {
        title: "Chart.js",
        icon: "https://no.buging.cn/img/chartjs.png",
        link: "https://www.chartjs.org/",
        desc: "一个简单、面向对象，为设计和开发者准备的图表绘制工具库",
      },
      {
        title: "Leaflet",
        icon: "https://no.buging.cn/img/leafletjs.png",
        link: "https://leafletjs.com/",
        desc: "一个用于移动端渲染交互式地图开源JavaScript库",
      },
      {
        title: "高德地图",
        icon: "https://a.amap.com/pc/static/favicon.ico",
        link: "https://lbs.amap.com/",
        desc: "高德地图开放平台",
      },
      {
        title: "百度地图",
        icon: "https://mapopen-website-wiki.cdn.bcebos.com/LOGO/lbsyunlogo_icon.ico",
        link: "https://lbsyun.baidu.com/",
        desc: "百度地图开放平台",
      },
      {
        title: "DataV组件版",
        icon: "http://datav.jiaminghi.com/favicon.ico",
        link: "http://datav.jiaminghi.com/",
        desc: "大屏数据展示组件库",
      },
    ],
  },
  {
    Category_id: "baseLearn",
    title: "学习资源",
    category_icon: "icon-xuexi",
    category_item: "baseLearnItem",
    items: [
      {
        title: "Mozilla 开发者网络",
        icon: "https://no.buging.cn/img/mozilla.jpg",
        link: "https://developer.mozilla.org/zh-CN/",
        desc: "MDN Web Docs 网站提供开放网络（Open Web）技术有关的信息，包括用于网站和渐进式网络应用的 HTML、CSS 和 API。",
      },
      {
        title: "freeCodeCamp中文社区",
        icon: "https://no.buging.cn/img/freecodecamp.png",
        link: "https://forum.freecodecamp.org/c/chinese/533",
        desc: " 一个帮助你学习编程的开源社区,开启你的软件工程师生涯.",
      },
      {
        title: "学习CSS布局",
        icon: "https://no.buging.cn/img/learnlayout.png",
        link: "http://zh.learnlayout.com/",
        desc: "本站教授的是现在广泛使用于网站布局领域的CSS基础。",
      },
      {
        title: "菜鸟教程",
        icon: "https://no.buging.cn/img/runoob.png",
        link: "http://www.runoob.com/",
        desc: "菜鸟教程,提供了编程的基础技术教程.学的不仅是技术，更是梦想！",
      },
      {
        title: "w3school",
        icon: "https://no.buging.cn/img/w3school.png",
        link: "http://www.w3school.com.cn/",
        desc: "w3school 在线教程 , 全球最大的中文 Web 技术教程。",
      },
      {
        title: "百度前端技术学院",
        icon: "https://no.buging.cn/img/ifebaidu.png",
        link: "http://ife.baidu.com/",
        desc: "百度前端技术学院是一个为大学生创办的免费的前端技术实践、分享、交平台。",
      },
      {
        title: "表严肃-不要水，讲干货",
        icon: "https://no.buging.cn/img/biaoyansu.png",
        link: "http://biaoyansu.com/",
        desc: "基础教程视频,B站良心up主,满满的干货.",
      },
      {
        title: "HEAD",
        icon: "https://no.buging.cn/img/head.png",
        link: "https://github.com/joshbuchea/HEAD",
        desc: "最全的 head 列表，真心佩服这种偏执的整理能力",
      },
      {
        title: "前端开发仓库",
        icon: "https://no.buging.cn/img/ciaoca.png",
        link: "http://code.ciaoca.com/",
        desc: "Web前端开发仓库，收录常用的JavaScript及jQuery插件，并提供在线演示效果。",
      },
      {
        title: "learnGitBranching",
        icon: "https://no.buging.cn/img/learnGitBranching.png",
        link: "https://github.com/pcottle/learnGitBranching",
        desc: "learnGitBranching是一个git仿真沙盒，提供一系列的交互式学习指导/挑战，用来加快学习git提交树如何工作。learnGitBranching的主界面左边是模拟终端窗口，另外是图示区。图示区用图形表明了git代码库当前的提交记录、分支、HEAD指向等。 目前有法语、韩语、日语以及中文版本。",
      },
      {
        title: "前端九部-入门者手册2019",
        icon: "https://no.buging.cn/img/fe9.png",
        link: "https://www.yuque.com/fe9/basic",
        desc: "九部成员合著的web前端开发零基础入门手册",
      },
      {
        title: "力扣-LeetCode",
        icon: "https://no.buging.cn/img/leetcode.png",
        link: "https://leetcode-cn.com/",
        desc: "码，码不停题. 全球极客挚爱的高质量技术成长平台，想要学习和提升专业能力从这里开始，充足技术干货等你来啃，轻松拿下 Dream Offer！",
      },
      {
        title: "前端周刊",
        icon: "https://no.buging.cn/img/frontenddevhandbook.png",
        link: "https://frontend-weekly.com/",
        desc: "前端周刊，给前端同学准备的每周1小时阅读清单",
      },
      {
        title: "Git的奇技淫巧",
        icon: "https://no.buging.cn/img/frontend-notebook.png",
        link: "https://github.com/521xueweihan/git-tips",
        desc: "列举了常用的 Git 命令和一些小技巧",
      },
    ],
  },
  {
    Category_id: "apiDoc",
    title: "文档API",
    category_icon: "icon-icon_bangzhuwendang",
    category_item: "apiDocItem",
    items: [
      {
        title: "HTML5",
        icon: "https://no.buging.cn/img/w3HTML5.png",
        link: "https://www.w3.org/html/ig/zh/wiki/HTML5",
        desc: "HTML5开发文档,开源(w3c组织)",
      },
      {
        title: "HTML5 + API",
        icon: "https://no.buging.cn/img/html5plus.png",
        link: "http://www.html5plus.org/doc/h5p.html",
        desc: "HTML5+规范,HTML5中国产业联盟",
      },
      {
        title: "CSS参考手册",
        icon: "https://no.buging.cn/img/doyoe.png",
        link: "http://css.doyoe.com/",
        desc: "Web前端开发人员提供最新、最全的CSS中文版在线资料，涵盖CSS3参考手册。",
      },
      {
        title: "NEC(CSS规范)",
        icon: "https://no.buging.cn/img/netease.png",
        link: "http://nec.netease.com/",
        desc: "NEC包括了规范、框架、代码库、插件等内容，致力于为前端开发人员提供高效率高质量的前端页面开发解决方案。",
      },
      {
        title: "jQuery API 中文文档",
        icon: "https://no.buging.cn/img/cuishifeng.jpg",
        link: "http://jquery.cuishifeng.cn/index.html",
        desc: "jQuery API 中文文档 | jQuery API 中文在线手册 | jquery api 载 | jquery api chm",
      },
      {
        title: "vue.js中文文档",
        icon: "https://no.buging.cn/img/vuejs.png",
        link: "https://cn.vuejs.org/",
        desc: "vue.js官方中文文档",
      },
      {
        title: "npm 中文文档",
        icon: "https://no.buging.cn/img/npmjs.png",
        link: "https://www.npmjs.cn/",
        desc: "npm 是 JavaScript 世界的包管理工具，并且是 Node.js 平台的默认包管理工具。通过 npm 可以安装、共享、分发代码，管理项目依赖关系。npm，是全球最大的开源库生态系统。",
      },
      {
        title: "Node.js 中文文档",
        icon: "https://no.buging.cn/img/nodeapp.png",
        link: "https://www.nodeapp.cn/",
        desc: "Node.js 是一个基于 Chrome V8 引擎的 JavaScript 运行环境。Node.js 使用了一个事件驱动、非阻塞式 I/O的模型，使其轻量又高效。Node.js 的包管理器",
      },
      {
        title: "React 中文文档",
        icon: "https://no.buging.cn/img/reactdocschina.png",
        link: "https://react.docschina.org/",
        desc: "用于构建用户界面的 JavaScript 库",
      },
      {
        title: "React Native 中文网",
        icon: "https://no.buging.cn/img/reactnative.png",
        link: "https://reactnative.cn/",
        desc: "使用JavaScript和React编写原生移动应用",
      },
      {
        title: "Node.js 中文网API",
        icon: "https://no.buging.cn/img/nodeapp.png",
        link: "http://nodejs.cn/api/",
        desc: "nodejs中文网中文文档",
      },
      {
        title: "Flutter",
        icon: "https://no.buging.cn/img/flutter.png",
        link: "https://flutterchina.club/",
        desc: "Flutter是谷歌的移动UI框架，可以快速在iOS和Android上构建高质量的原生用户界面。",
      },
      {
        title: "html5 Platform",
        icon: "https://no.buging.cn/img/platform.png",
        link: "https://platform.html5.org/",
        desc: "HTML5的web浏览技术图谱",
      },
    ],
  },
  {
    Category_id: "portalsCommunity",
    title: "门户&社区",
    category_icon: "icon-songmenhuwangzhan",
    category_item: "portalsCommunityItem",
    items: [
      {
        title: "GitHub",
        icon: "https://no.buging.cn/img/github.png",
        link: "https://github.com/",
        desc: "一个面向开源及私有软件项目的托管平台,全球最大同性交友网站",
      },
      {
        title: "Stack Overflow",
        icon: "https://no.buging.cn/img/StackOverflow.png",
        link: "https://stackoverflow.com/",
        desc: "全球最大的技术问答网站，是一个与程序相关的IT技术问答网站",
      },
      {
        title: "掘金 - juejin.im",
        icon: "https://no.buging.cn/img/juejin.png",
        link: "https://juejin.im/welcome/frontend",
        desc: "一个帮助开发者成长的社区",
      },
      {
        title: "SegmentFault 思否",
        icon: "https://no.buging.cn/img/segmentfault.png",
        link: "https://segmentfault.com/channel/frontend",
        desc: "SegmentFault 思否 为开发者提供问答、学习与交流编程知识的平台，创造属于开发者的时代！",
      },
      {
        title: "博客园",
        icon: "https://no.buging.cn/img/cnblogs.png",
        link: "https://www.cnblogs.com/",
        desc: "博客园是一个面向开发者的知识分享社区。",
      },
      {
        title: "v2ex",
        icon: "https://no.buging.cn/img/v2ex.png",
        link: "https://www.v2ex.com/",
        desc: "一个关于分享和探索的地方",
      },
      {
        title: "InfoQ",
        icon: "https://no.buging.cn/img/infoq.png",
        link: "https://www.infoq.cn/",
        desc: "InfoQ 是一个实践驱动的社区资讯站点，致力于促进软件开发领域知识与创新的传播。",
      },
      {
        title: "IBM-developerworks",
        icon: "https://no.buging.cn/img/IBMdeveloperworks.png",
        link: "https://www.ibm.com/developerworks/cn/",
        desc: "IBM developerWorks，IBM 的官方开发者项目。学习资源，开发工具，和技术社区。",
      },
      {
        title: "知乎",
        icon: "https://no.buging.cn/img/zhihu.png",
        link: "https://www.zhihu.com/",
        desc: "每日必刷，可以关注前端开发等话题",
      },
      {
        title: "开源中国",
        icon: "https://no.buging.cn/img/oschina.png",
        link: "https://www.oschina.net/",
        desc: "开源中国 www.oschina.net 是目前中国最大的开源技术社区。",
      },
      {
        title: "W3Cways",
        icon: "https://no.buging.cn/img/w3cways.png",
        link: "https://www.w3cways.com/",
        desc: "Web前端学习之路，网站提供很丰富的相关技术中文文档。",
      },
      {
        title: "Helloweba",
        icon: "https://no.buging.cn/img/helloweba.png",
        link: "https://www.helloweba.net/",
        desc: "Helloweba为广大WEB开发者提供Javascript前端、PHP后端、服务器运维知识以及业界相关的高质量技术文章分享.",
      },
      {
        title: "PHP中文网",
        icon: "https://no.buging.cn/img/phpcn.png",
        link: "http://www.php.cn/",
        desc: "php中文网-教程_手册_视频-免费php在线学习平台.",
      },
      {
        title: "前端里",
        icon: "https://no.buging.cn/img/yyyweb.png",
        link: "http://www.yyyweb.com/",
        desc: "专注于分享最前沿的Web开发技术，教程，资源和素材，是面向网站开发人员和设计师的学习交流平台",
      },
    ],
  },
  {
    Category_id: "organization",
    title: "组织团队",
    category_icon: "icon-zuzhi",
    category_item: "organizationItem",
    items: [
      {
        title: "万维网联盟W3C",
        icon: "https://no.buging.cn/img/w3.png",
        link: "https://www.w3.org/",
        desc: "万维网联盟创建于1994年，是Web技术领域最具权威和影响力的国际中立性技术标准机构。",
      },
      {
        title: "奇舞团",
        icon: "https://no.buging.cn/img/75team.png",
        link: "https://75team.com/",
        desc: "奇虎360公司Web平台部前端工程师 + 部分特约嘉宾 组成的一个前端团队。",
      },
      {
        title: "百度EFE",
        icon: "https://no.buging.cn/img/efebaidu.png",
        link: "http://efe.baidu.com/",
        desc: "百度EFE技术体系，前身是ECOM前端团队，后经过技术的发展，逐渐形成一套完善的前端技术体系。",
      },
      {
        title: "淘宝前端团队(FED)",
        icon: "https://no.buging.cn/img/taobaofed.png",
        link: "http://taobaofed.org/",
        desc: "淘宝前端团队，用技术为体验提供无限可能。",
      },
      {
        title: "腾讯AlloyTeam",
        icon: "https://no.buging.cn/img/alloyteam.png",
        link: "http://www.alloyteam.com/",
        desc: "来自于腾讯SNG(社交网络事业群)，是主要负责腾讯Q+、WebQQ、QQ群空间项目的团队，致力于Web前端技术的研究。",
      },
      {
        title: "百度FEX",
        icon: "https://no.buging.cn/img/fexbaidu.png",
        link: "http://fex.baidu.com/",
        desc: "FEX 是百度Web 前端研发部的别名，是社区基础技术部中的前端团队。",
      },
      {
        title: "凹凸实验室",
        icon: "https://no.buging.cn/img/aotu.png",
        link: "https://aotu.io/",
        desc: "京东用户体验设计部出品",
      },
      {
        title: "阿里巴巴国际UED团队",
        icon: "https://no.buging.cn/img//aliued.jpg",
        link: "http://www.aliued.com/",
        desc: "在更新的屏幕里创造出更好的产品和更优的体验",
      },
      {
        title: "阿里妈妈MUX",
        icon: "https://no.buging.cn/img/alimama.png",
        link: "https://mux.alimama.com/posts/front-end.html",
        desc: "阿里妈妈MUX - UX 体验工作平台",
      },
      {
        title: "去哪儿网 UED",
        icon: "https://no.buging.cn/img/qunar.jpg",
        link: "http://ued.qunar.com/",
        desc: "Qunar UED, 去哪儿, 前端, FE, FED, UED",
      },
      {
        title: "美团技术团队",
        icon: "https://no.buging.cn/img/meituan.png",
        link: "https://tech.meituan.com/",
        desc: "美团点评技术团队",
      },
      {
        title: "大搜车无线团队",
        icon: "https://no.buging.cn/img/souche.png",
        link: "http://f2e.souche.com/blog/",
        desc: "前端网红 小芋头君 所在的团队，文章质量高，尤其是 Node 方向的",
      },
      {
        title: "微软开发者网络MSDN",
        icon: "https://no.buging.cn/img/msdnmicrosoft.png",
        link: "https://msdn.microsoft.com/zh-cn/",
        desc: "使用 Microsoft Developer Network 学习开发 | MSDN",
      },
      {
        title: "印记中文",
        icon: "https://no.buging.cn/img/docschina.png",
        link: "https://www.docschina.org/",
        desc: "收集了由社区翻译的比较流行的前端相关框架、工具的中文版文档。为学习一些新的框架扫平了语言障碍",
      },
    ],
  },
  {
    Category_id: "codeSource",
    title: "代码素材/片段",
    category_icon: "icon-daima",
    category_item: "codeSourceItem",
    items: [
      {
        title: "microjs",
        icon: "https://no.buging.cn/img/microjs.png",
        link: "http://microjs.com/#",
        desc: "迷你前端开发框架和类库资源收集,前端开发工程师必备的网站, 网站收集了各种各样的框架和代码",
      },
      {
        title: "jQuery插件库",
        icon: "https://no.buging.cn/img/jq22.png",
        link: "http://www.jq22.com/",
        desc: "致力于收集jQuery插件和提供各种jQuery特效的详细使用方法,在线预览，jQuery插件下载及教程",
      },
      {
        title: "JQuerySchool",
        icon: "https://no.buging.cn/img/jq-school.png",
        link: "http://www.jq-school.com/",
        desc: "jqueryschool是国内最大的jquery原创分享社区，专门分享原创jquery插件、jquery工具、jquery特效、html5、css3、jquery教程的网站，分享原创设计，把开发代码封装成插件，最短时间掌握jquery知识。",
      },
      {
        title: "jQuery之家",
        icon: "https://no.buging.cn/img/htmleaf.png",
        link: "http://www.htmleaf.com/",
        desc: "搜集和整理各种jQuery插件，jQuery特效，jquery ui，jQuery教程，JS特效，网页特效，以及各种html5，css3动画和效果，为前端开发者提供最全面的网页开发素材。",
      },
      {
        title: "dowebok",
        icon: "https://no.buging.cn/img/dowebok.png",
        link: "http://www.dowebok.com/",
        desc: "dowebok意为做好网站，为用户提供代码、素材、特效、教程、模板等建站服务。",
      },
      {
        title: "模板之家",
        icon: "https://no.buging.cn/img/cssmoban.png",
        link: "http://www.cssmoban.com/",
        desc: "CSS模板之家为你提供大量精品网页模板,企业网站模板,网站模板下载,DIV+CSS模板,网页设计模板,网站后台模板,个人博客模板,上千种免费网页模板下载",
      },
      {
        title: "Html5 Tricks",
        icon: "https://no.buging.cn/img/html5tricks.png",
        link: "https://www.html5tricks.com/",
        desc: "很多前端实现的功能，可以在线查看效果，也可以下载源码",
      },
      {
        title: "codemyui",
        icon: "https://no.buging.cn/img/codemyui.png",
        link: "https://codemyui.com/",
        desc: "采集有趣的网站UI代码片段",
      },
      {
        title: "PlainJS",
        icon: "https://no.buging.cn/img/plainjs.png",
        link: "https://plainjs.com/",
        desc: "该仓库都是用原生js写的插件和组件，很实用",
      },
      {
        title: "Snippets",
        icon: "https://no.buging.cn/img/snippets.png",
        link: "http://snippets.barretlee.com/#!/snippets",
        desc: "小胡子哥的代码收藏夹，Snippets 管理工具",
      },
    ],
  },
  {
    Category_id: "templatePlug",
    title: "模板插件",
    category_icon: "icon-chajian2",
    category_item: "templatePlugItem",
    items: [
      {
        title: "Swiper",
        icon: "https://no.buging.cn/img/swiper.png",
        link: "https://www.swiper.com.cn/",
        desc: "目前应用较广泛的移动端网页触摸内容滑动js插件",
      },
      {
        title: "art-template",
        icon: "https://no.buging.cn/img/art-template.png",
        link: "https://github.com/aui/art-template",
        desc: "一个简约、超快的模板引擎。它采用作用域预声明的技术来优化模板渲染速度，从而获得接近 JavaScript 极限的运行性能，并且同时支持 NodeJS 和浏览器。",
      },
      {
        title: "iScroll",
        icon: "https://no.buging.cn/img/iScroll.png",
        link: "https://github.com/cubiq/iscroll",
        desc: "一个高性能，资源占用少，无依赖，多平台的javascript滚动插件",
      },
      {
        title: "fullPage.js",
        icon: "https://no.buging.cn/img/fullPage.png",
        link: "https://alvarotrigo.com/fullPage/zh/",
        desc: "一个基于 jQuery 的插件,它能够很方便、很轻松的制作出全屏网站。",
      },
      {
        title: "Lightbox",
        icon: "https://no.buging.cn/img/lightbox.png",
        link: "https://lokeshdhakar.com/projects/lightbox2/",
        desc: "以弹框形式集中展示图片的JavaScript库。",
      },
      {
        title: "Siema",
        icon: "https://no.buging.cn/img/siema.jpg",
        link: "https://pawelgrzybek.github.io/siema/",
        desc: "轻量级简单的纯 JavaScript 轮播插件，支持触摸手势",
      },
      {
        title: "Datatables",
        icon: "https://no.buging.cn/img/datatables.jpg",
        link: "http://datatables.club/",
        desc: "Datatables是一款jquery表格插件，它是一个高度灵活的工具，可以将任何HTML表格添加高级的交互功能。",
      },
      {
        title: "Waterfall",
        icon: "https://no.buging.cn/img/waterfall.jpg",
        link: "http://wlog.cn/waterfall/index-zh.html",
        desc: "一款仿Pinterest网站的响应式无限动态加载图片瀑布流特效jQuery插件",
      },
      {
        title: "Sticker.js",
        icon: "https://no.buging.cn/img/stickerjs.jpg",
        link: "http://stickerjs.cmiscm.com/",
        desc: "一款仿贴纸效果插件。",
      },
      {
        title: "multiScroll.js",
        icon: "https://no.buging.cn/img/multiScroll.jpg",
        link: "https://alvarotrigo.com/multiScroll/#first",
        desc: "创建分割的多滚动页面特效插件。",
      },
      {
        title: "jQuery File Upload Plugin",
        icon: "https://no.buging.cn/img/jQuery-File-Upload.png",
        link: "https://blueimp.github.io/jQuery-File-Upload/",
        desc: "一个有功能强大的 jQuery 上传组件，支持多文件选择、拖拽上传、验证、图片和多媒体预览等功能。",
      },
      {
        title: "Interact.js",
        icon: "https://no.buging.cn/img/interactjs.png",
        link: "http://interactjs.io/",
        desc: " interact.js是一个随意改变形状插件，,它非常强大的，灵活拖放，改变大小，支持现代浏览器的多点触摸手势，基于SVG的运用，能运行在包括在IE8+的浏览器",
      },
      {
        title: "Background-blur",
        icon: "https://no.buging.cn/img/background-blur.jpg",
        link: "https://msurguy.github.io/background-blur/#",
        desc: "实用的超轻的跨浏览器的图像模糊 jQuery 插件，基于 SVG 生成，效果很好",
      },
      {
        title: "blur-admin",
        icon: "https://no.buging.cn/img/blur-admin.png",
        link: "https://github.com/akveo/blur-admin",
        desc: "视觉冲击极强的管理后台，各种动画效果。",
      },
      {
        title: "Holder.js",
        icon: "https://no.buging.cn/img/holderjs.png",
        link: "https://github.com/imsky/holder",
        desc: "占位图片生成器",
      },
      {
        title: "placeholder.js",
        icon: "https://no.buging.cn/img/placeholder.png",
        link: "https://github.com/hustcc/placeholder.js",
        desc: "另一款占位图片生成器",
      },
      {
        title: "Echo.js",
        icon: "https://no.buging.cn/img/echojs.png",
        link: "https://github.com/toddmotto/echo",
        desc: "简单的JavaScript轻量级图像延迟加载库",
      },
      {
        title: "jQuery-LazyLoad",
        icon: "https://no.buging.cn/img/jquery_lazyload.png",
        link: "https://github.com/tuupola/jquery_lazyload/",
        desc: "基于 jQuery 的图片延迟加载插件，在用户滚动页面到图片之后才进行加载。对于有较多的图片的网页，使用图片延迟加载，能有效的提高页面加载速度",
      },
      {
        title: "imagesLoaded",
        icon: "https://no.buging.cn/img/imagesloaded.png",
        link: "https://github.com/desandro/imagesloaded",
        desc: "检测图片是否加载完成的插件",
      },
      {
        title: "quicklink",
        icon: "https://no.buging.cn/img/quicklink.png",
        link: "https://github.com/GoogleChromeLabs/quicklink",
        desc: "quicklink 是一个通过预加载资源来提升后续方案速度的轻量级工具库。旨在提升浏览过程中，用户访问后续页面时的加载速度。",
      },
      {
        title: "AJAX-Cache",
        icon: "https://no.buging.cn/img/ajax-cache.png",
        link: "https://github.com/tower1229/AJAX-Cache",
        desc: "AJAX-Cache是一款jQuery插件，基于localStorage/sessionStorage实现异步请求缓存功能，并提供“快照”和“定时”两种缓存模式。",
      },
    ],
  },
  {
    Category_id: "ide",
    title: "编辑器/IDE",
    category_icon: "icon-shebeikaifa",
    category_item: "ideItem",
    items: [
      {
        title: "Sublime Text",
        icon: "https://no.buging.cn/img/sublimetext.png",
        link: "http://www.sublimetext.com/",
        desc: "神级代码编辑软件(Sublime Text 3),SublimeText是一个代码编辑器。也是HTML和散文先进的文本编辑器。",
      },
      {
        title: "Visual Studio Code",
        icon: "https://no.buging.cn/img/vscode.png",
        link: "https://code.visualstudio.com/",
        desc: "一款免费开源的现代化轻量级代码编辑器，支持几乎所有主流的开发语言的语法高亮、智能代码补全、自定义热键、括号匹配、代码片段、代码对比 Diff、GIT等特性，支持插件扩展，并针对网页开发和云端应用开发做了优化。。",
      },
      {
        title: "Webstorm",
        icon: "https://no.buging.cn/img/webstorm.png",
        link: "http://www.jetbrains.com/webstorm/",
        desc: "jetbrains公司旗下一款JavaScript 开发工具。目前已经被广大中国JS开发者誉为“Web前端开发神器",
      },
      {
        title: "Atom",
        icon: "https://no.buging.cn/img/atom.png",
        link: "https://atom.io/",
        desc: "Atom 是github专门为程序员推出的一个跨平台文本编辑器。",
      },
      {
        title: "HBuilder",
        icon: "https://no.buging.cn/img/dcloud.png",
        link: "http://www.dcloud.io/",
        desc: "HBuilder是当前最快的HTML开发工具,强大的代码助手帮你快速完成开发,最全的语法库和浏览器兼容性数据让浏览器碎片化不再头痛",
      },
      {
        title: "Vim",
        icon: "https://no.buging.cn/img/vim.png",
        link: "https://www.vim.org/",
        desc: "Vim是一个类似于Vi的著名的功能强大、高度可定制的文本编辑器，在Vi的基础上改进和增加了很多特性。",
      },
      {
        title: "Notepad++",
        icon: "https://no.buging.cn/img/notepad.png",
        link: "https://notepad-plus-plus.org/",
        desc: "Notepad++是 Windows操作系统下的一套文本编辑器(软件版权许可证: GPL),有完整的中文化接口及支持多国语言编写的功能(UTF8技术)。",
      },
      {
        title: "HBuilderX",
        icon: "https://no.buging.cn/img/hbuilderx.png",
        link: "http://www.dcloud.io/hbuilderx.html",
        desc: "HBuilderX，简称HX，是轻如编辑器、强如IDE的合体版本",
      },
    ],
  },
  {
    Category_id: "fontIco",
    title: "字体图标",
    category_icon: "icon-font",
    category_item: "fontIcoItem",
    items: [
      {
        title: "iconfont",
        icon: "https://no.buging.cn/img/iconfont.png",
        link: "https://www.iconfont.cn/",
        desc: "阿里妈妈MUX打造的图标库，是国内功能很强大且图标内容很丰富的矢量图标库。",
      },
      {
        title: "Font Awesome",
        icon: "https://one.one.one.one/favicon.ico",
        link: "http://fontawesome.dashgame.com/",
        desc: "一款风靡全球的图标字体库和CSS框架。",
      },
      {
        title: "icomoon",
        icon: "https://no.buging.cn/img/icomoon.png",
        link: "https://icomoon.io/",
        desc: "免费开源的字体图标库。",
      },
      {
        title: "MFG Labs icon set",
        icon: "https://no.buging.cn/img/mfglabs.png",
        link: "http://mfglabs.github.io/mfglabs-iconset/",
        desc: "免费字体图标",
      },
      {
        title: "FindIcons",
        icon: "https://no.buging.cn/img/findicons.png",
        link: "https://findicons.com/",
        desc: "免费图标和矢量文件",
      },
      {
        title: "iconmonstr",
        icon: "https://no.buging.cn/img/iconmonstr.png",
        link: "https://iconmonstr.com/",
        desc: "外国字体图标网站,为项目提供免费的简单图标",
      },
      {
        title: "FLATICON",
        icon: "https://no.buging.cn/img/FLATICON.png",
        link: "https://www.flaticon.com/",
        desc: "icon下载",
      },
      {
        title: "ICONFINDER",
        icon: "https://no.buging.cn/img/iconfinder.png",
        link: "https://www.iconfinder.com/",
        desc: "高质量付费图标下载",
      },
      {
        title: "Noun Project",
        icon: "https://no.buging.cn/img/thenounproject.png",
        link: "https://thenounproject.com/",
        desc: "icon下载",
      },
      {
        title: "RPG-Awesome",
        icon: "https://no.buging.cn/img/RpgAwesome.png",
        link: "http://nagoshiashumari.github.io/Rpg-Awesome/",
        desc: "icon下载",
      },
      {
        title: "Orion Icon Library",
        icon: "https://no.buging.cn/img/orioniconlibrary.png",
        link: "https://orioniconlibrary.com/",
        desc: "多达6000专业免费的SVG矢量图标，还支持深度的定制，比如更换配色，更改线条粗细，变换图标风格(细线条、粗线条、扁平)，一键生成相关代码。",
      },
      {
        title: "gitmoji",
        icon: "https://no.buging.cn/img/gitmoji.png",
        link: "https://gitmoji.carloscuesta.me/",
        desc: "可以使用在github上的emoji图标",
      },
      {
        title: "Emoji Cheat Sheet",
        icon: "https://no.buging.cn/img/emoji-cheat-sheet.png",
        link: "https://www.webfx.com/tools/emoji-cheat-sheet/",
        desc: "可以使用在github上的emoji图标",
      },
      {
        title: "Emoji searcher",
        icon: "https://no.buging.cn/img/Emojisearcher.png",
        link: "https://emoji.muan.co/",
        desc: "Emoji表情大全",
      },
      {
        title: "草莓图标库",
        icon: "https://no.buging.cn/img/chuangzaoshi.png",
        link: "http://chuangzaoshi.com/icon/",
        desc: "为开发者设计的一套免费开源图标库",
      },
      {
        title: "Unicons",
        icon: "https://no.buging.cn/img/unicons.png",
        link: "https://iconscout.com/unicons",
        desc: "超過 1000 個向量圖示免費下載，完美像素放大縮小不影響解析度",
      },
      {
        title: "Ikonate",
        icon: "https://no.buging.cn/img/ikonate.png",
        link: "https://www.ikonate.com/",
        desc: "完全可定制的矢量图标",
      },
    ],
  },
  {
    Category_id: "vision",
    title: "视觉设计",
    category_icon: "icon-shijuesheji",
    category_item: "visionItem",
    items: [
      {
        title: "Color Hunt",
        icon: "https://no.buging.cn/img/colorhunt.png",
        link: "https://colorhunt.co/",
        desc: "网站配色专家",
      },
      {
        title: "Dribbble",
        icon: "https://no.buging.cn/img/dribbble.png",
        link: "https://dribbble.com/",
        desc: "设计灵感",
      },
      {
        title: "Pixabay",
        icon: "https://no.buging.cn/img/pixabay.png",
        link: "https://pixabay.com/",
        desc: "全球最大的免费可商用高清图库网站，超过130万张免费的优质图片及视频素材。",
      },
      {
        title: "StockSnap.io",
        icon: "https://no.buging.cn/img/stocksnap.png",
        link: "https://stocksnap.io/",
        desc: "高清免费大图素材，不用登陆直接可以下载，每周更新超过百张高清免费图片。",
      },
      {
        title: "罫線・飾り罫ライン素材",
        icon: "https://no.buging.cn/img/free-line-design.png",
        link: "http://free-line-design.com/",
        desc: "分割线素材",
      },
      {
        title: "loading.io",
        icon: "https://no.buging.cn/img/loading.io.png",
        link: "https://loading.io/",
        desc: "loading图生成",
      },
      {
        title: "pngimg",
        icon: "https://no.buging.cn/img/pngimg.png",
        link: "http://pngimg.com/",
        desc: "pngimg图片素材",
      },
      {
        title: "Color Hex",
        icon: "https://no.buging.cn/img/colorhexa.png",
        link: "https://www.colorhexa.com/",
        desc: "配色网",
      },
      {
        title: "flatuicolors",
        icon: "https://no.buging.cn/img/flatuicolors.png",
        link: "https://flatuicolors.com/",
        desc: "扁平化配色",
      },
      {
        title: "Subtle Patterns",
        icon: "https://no.buging.cn/img/SubtlePatterns.png",
        link: "https://www.toptal.com/designers/subtlepatterns/",
        desc: "Patterns素材,网页背景图",
      },
      {
        title: "Pttrns",
        icon: "https://no.buging.cn/img/pttrns.png",
        link: "https://pttrns.com/",
        desc: "App界面灵感",
      },
      {
        title: "Lapa",
        icon: "https://no.buging.cn/img/lapa.png",
        link: "https://www.lapa.ninja/",
        desc: "产品官网、落地页设计欣赏",
      },
      {
        title: "Cool Backgrounds",
        icon: "https://no.buging.cn/img/coolbackgrounds.png",
        link: "https://coolbackgrounds.io/",
        desc: "生成非常酷的彩色背景图像",
      },
      {
        title: "freeimages",
        icon: "https://static.freeimages.com/favicon/favicon-32x32.png",
        link: "https://www.freeimages.com/",
        desc: "下载免费高品质的 PSD 文件、插图和图形。浏览我们的图库，快速找到心仪图像，商业使用完全免费。",
      },
      {
        title: "UIgradients",
        icon: "https://no.buging.cn/img/uigradients.png",
        link: "https://uigradients.com/",
        desc: "简洁舒服的渐变配色",
      },
      {
        title: "Freebiesbug",
        icon: "https://no.buging.cn/img/freebiesbug.png",
        link: "https://freebiesbug.com/",
        desc: "高质量设计网站、资源聚合站点",
      },
      {
        title: "OnePageLove",
        icon: "https://no.buging.cn/img/onepagelove.png",
        link: "https://onepagelove.com/",
        desc: "网站和APP单页界面欣赏",
      },
      {
        title: "UpLabs",
        icon: "https://no.buging.cn/img/uplabs.png",
        link: "https://www.uplabs.com/",
        desc: "采集前端作品设计、iOS UI设计",
      },
      {
        title: "Reeoo",
        icon: "https://no.buging.cn/img/reeoo.png",
        link: "http://reeoo.com/",
        desc: "全球最火热的酷站画廊",
      },
      {
        title: "SiteSee",
        icon: "https://no.buging.cn/img/sitesee.png",
        link: "https://sitesee.co/",
        desc: "收录漂亮的界面设计网站",
      },
      {
        title: "Calltoidea",
        icon: "https://no.buging.cn/img/calltoidea.png",
        link: "https://www.calltoidea.com/",
        desc: "收集优秀UI组件元素设计的站点",
      },
      {
        title: "Wallroom",
        icon: "https://no.buging.cn/img/wallroom.png",
        link: "https://wallroom.io/",
        desc: "精美壁纸网站,壁纸分为了1K、2K、4K、5K、8K",
      },
    ],
  },
  {
    Category_id: "blog",
    title: "大牛博客",
    category_icon: "icon-fanshe",
    category_item: "blogItem",
    items: [
      {
        title: "阮一峰",
        icon: "https://no.buging.cn/img/ruanyifeng.png",
        link: "http://www.ruanyifeng.com/home.html",
        desc: "阮一峰的个人网站 - Ruan YiFeng's Personal Website",
      },
      {
        title: "廖雪峰",
        icon: "https://no.buging.cn/img/liaoxuefeng.png",
        link: "https://www.liaoxuefeng.com/",
        desc: "研究互联网产品和技术，提供原创中文精品教程",
      },
      {
        title: "张鑫旭",
        icon: "https://no.buging.cn/img/zhangxinxu.png",
        link: "https://www.zhangxinxu.com/",
        desc: "张鑫旭的个人博客首页，张鑫旭的技术作品，张鑫旭的生活成长",
      },
      {
        title: "尤雨溪",
        icon: "https://no.buging.cn/img/evanyou.png",
        link: "https://evanyou.me/",
        desc: "Design, Code & Things in Between",
      },
      {
        title: "颜海镜",
        icon: "https://no.buging.cn/img/yanhaijing.png",
        link: "https://yanhaijing.com/",
        desc: "颜海镜的博客,专注于web前端",
      },
      {
        title: "周爱民",
        icon: "https://no.buging.cn/img/aimingoo.png",
        link: "https://aimingoo.github.io/",
        desc: "JavaScript语言精髓与编程实践作者",
      },
      {
        title: "技术胖",
        icon: "https://no.buging.cn/img/jspang.png",
        link: "https://jspang.com/",
        desc: "技术胖,该站有很多免费的前端学习视频",
      },
      {
        title: "勾三股四",
        icon: "https://no.buging.cn/img/jiongks.png",
        link: "http://jiongks.name/",
        desc: " 淘宝",
      },
      {
        title: "CSS森林",
        icon: "https://no.buging.cn/img/cssforest.png",
        link: "https://www.cssforest.org/",
        desc: "腾讯优秀前端重构,网站/页面重构",
      },
      {
        title: "叶小钗",
        icon: "https://no.buging.cn/img/yexiaochai.png",
        link: "http://www.cnblogs.com/yexiaochai",
        desc: "刀狂剑痴叶小钗",
      },
      {
        title: "雅X共赏",
        icon: "https://no.buging.cn/img/yaxgongshang.png",
        link: "https://refined-x.com/",
        desc: "枪在手，跟我走，前端路上不回头",
      },
    ],
  },
  {
    Category_id: "chrome",
    title: "chrome插件",
    category_icon: "icon-iconset0284",
    category_item: "chromeItem",
    items: [
      {
        title: "Chrome插件英雄榜",
        icon: "https://no.buging.cn/img/ChromeAppHeroes.png",
        link: "https://zhaoolee.gitbooks.io/chrome/content/",
        desc: "为优秀的Chrome插件写一本中文说明书, 让Chrome插件英雄们造福人类",
      },
      {
        title: "WEB前端助手(FeHelper)",
        icon: "https://no.buging.cn/img/FeHelper.png",
        link: "https://chrome.google.com/webstore/detail/web%E5%89%8D%E7%AB%AF%E5%8A%A9%E6%89%8Bfehelper/pkgccpejnmalmdinmhkkfafefagiiiad?hl=zh-CN",
        desc: "前端实用工具集，谁用谁知道！",
      },
      {
        title: "Image Downloader",
        icon: "https://no.buging.cn/img/ImageDownloader.png",
        link: "https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj?hl=zh-CN",
        desc: "一款能够查看网页中包含的所有图像和链接，并支持图片批量下载的chrome插件。",
      },
      {
        title: "Vue.js devtools",
        icon: "https://no.buging.cn/img/Vue.js devtools.png",
        link: "https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=zh-CN",
        desc: "基于google chrome浏览器的一款调试vue.js应用的开发者浏览器扩展",
      },
      {
        title: "ColorZilla",
        icon: "https://no.buging.cn/img/ColorZilla.png",
        link: "https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp?hl=zh-CN",
        desc: "为设计师提供了一种简单的浏览器平台工具来找到具体颜色数值并且测量它们的不同",
      },
      {
        title: "JSONView",
        icon: "https://no.buging.cn/img/JSONView.png",
        link: "https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=zh-CN",
        desc: "一款非常实用的格式化和语法高亮JSON格式数据查看器jQuery插件。它是查看json数据的神器。",
      },
      {
        title: "Markdown Viewer",
        icon: "https://no.buging.cn/img/MarkdownViewer.png",
        link: "https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk?hl=zh-CN",
        desc: "在浏览器中查看markdown文档,免去应用之间的切换",
      },
      {
        title: "Wappalyzer",
        icon: "https://no.buging.cn/img/wappalyzer.png",
        link: "https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg",
        desc: "分析目标网站所采用的平台构架、网站环境、服务器配置环境、JavaScript框架、编程语言等参数的chrome网站技术分析插件",
      },
      {
        title: "Octotree",
        icon: "https://no.buging.cn/img/octotree.png",
        link: "https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US",
        desc: "超实用的GitHub可视化代码树插件",
      },
      {
        title: "Ghelper",
        icon: "https://no.buging.cn/img/ghelper.png",
        link: "https://chrome.google.com/webstore/detail/%E8%B0%B7%E6%AD%8C%E4%B8%8A%E7%BD%91%E5%8A%A9%E6%89%8B-%E5%BC%80%E5%8F%91%E7%89%88/cieikaeocafmceoapfogpffaalkncpkc?hl=en-US",
        desc: "可以免费使用谷歌系列服务的插件",
      },
    ],
  },
  {
    Category_id: "aidedDevTools",
    title: " 辅助开发工具",
    category_icon: "icon-hebingxingzhuang-",
    category_item: "aidedDevToolsItem",
    items: [
      {
        title: "Getman",
        icon: "https://no.buging.cn/img/getman.png",
        link: "https://getman.cn",
        desc: "在线接口测试,模拟接口,正则匹配",
      },
      {
        title: "Easy Mock",
        icon: "https://no.buging.cn/img/easymock.png",
        link: "https://github.com/easy-mock/easy-mock",
        desc: "Easy Mock 是一个可视化, 并且能快速生成模拟数据的持久化服务.",
      },
      {
        title: "YAPI",
        icon: "https://no.buging.cn/img/yapi.png",
        link: "https://hellosean1025.github.io/yapi/",
        desc: "YApi 是高效、易用、功能强大的 api 管理平台，旨在为开发、产品、测试人员提供更优雅的接口管理服务。",
      },
      {
        title: "开发工具箱",
        icon: "https://no.buging.cn/img/box3.png",
        link: "http://www.box3.cn/",
        desc: "这个网站集合了各种工具，相信总有一款你用得上。",
      },
      {
        title: "CodePen",
        icon: "https://no.buging.cn/img/codepen.png",
        link: "https://codepen.io/",
        desc: "CodePen是浏览器中的HTML，CSS和JavaScript代码编辑器，可即时预览查看和编写您的代码。",
      },
      {
        title: "JS Bin",
        icon: "https://no.buging.cn/img/jsbin.png",
        link: "http://jsbin.com/",
        desc: "一个在线网站代码调试工具，主要用于测试 JavaScript 和 CSS 的代码片段的Web 应用，拥有简单的操作界面和全面的测试环境。",
      },
      {
        title: "PageSpeed Insights",
        icon: "https://no.buging.cn/img/pagespeedinsights.png",
        link: "https://developers.google.com/speed/pagespeed/insights/",
        desc: "Google在线性能测试网站、优化建议",
      },
      {
        title: "Responsinator",
        icon: "https://no.buging.cn/img/responsinator.png",
        link: "http://www.responsinator.com/",
        desc: "各大尺寸设备响应式屏幕效果显示",
      },
      {
        title: "Browser Sandbox",
        icon: "https://no.buging.cn/img/BrowserSandbox.png",
        link: "https://turbo.net/browsers",
        desc: "各大平台浏览器兼容性在线测试",
      },
      {
        title: "17ce网站测速",
        icon: "https://no.buging.cn/img/17ce.png",
        link: "https://www.17ce.com/",
        desc: "测试网站在全国各地和海外的打开速度，全面的报表功能、对比功能、地图展示、柱型图展示等专业测速网站",
      },
      {
        title: "IPIP.NET",
        icon: "https://no.buging.cn/img/ipip.png",
        link: "https://www.ipip.net/",
        desc: "最专业的 IP 地址库,该站有许多ip类工具",
      },
      {
        title: "Codelf",
        icon: "https://no.buging.cn/img/codelf.png",
        link: "https://unbug.github.io/codelf/",
        desc: "Codelf,变量命名,函数命名,方法命名,变量命名神器",
      },
    ],
  },
  {
    Category_id: "otherTools",
    title: " 其他工具",
    category_icon: "icon-gongju1",
    category_item: "otherToolsItem",
    items: [
      {
        title: "SM.MS",
        icon: "https://no.buging.cn/img/smms.png",
        link: "https://sm.ms/",
        desc: "图床网站,无外链限制，无流量限制",
      },
      {
        title: "Cutterman",
        icon: "https://no.buging.cn/img/cutterman.png",
        link: "http://www.cutterman.cn/zh/cutterman",
        desc: "最好用的切图工具,它是免费的,就是这么任性! 此站很多神器。",
      },
      {
        title: "font-face generator",
        icon: "https://no.buging.cn/img/font-face-generator.png",
        link: "https://everythingfonts.com/font-face",
        desc: "@font-face网页字体文件格式转换",
      },
      {
        title: "TinyPNG",
        icon: "https://no.buging.cn/img/tinypng.png",
        link: "https://tinypng.com/",
        desc: "超完美PNG压缩工具",
      },
      {
        title: "BrowserFrame",
        icon: "https://no.buging.cn/img/browserframe.png",
        link: "https://browserframe.com/",
        desc: "一个生成浏览器外壳的网站，它提供了两种方式来生成截图",
      },
      {
        title: "Carbon",
        icon: "https://no.buging.cn/img/carbon.png",
        link: "https://carbon.now.sh",
        desc: "代码界美图秀秀,装逼用",
      },
      {
        title: "easy PDF",
        icon: "https://no.buging.cn/img/easypdf.png",
        link: "https://easypdf.com/cn",
        desc: "在线 PDF 转换工具",
      },
      {
        title: "有道云笔记",
        icon: "https://no.buging.cn/img/youdaonote.png",
        link: "https://note.youdao.com/web",
        desc: "个人觉得比印象笔记好用的云笔记",
      },
      {
        title: "SVG To PNG",
        icon: "https://svgtopng.com/images/svgtopng/favicon.png",
        link: "https://svgtopng.com/zh/",
        desc: "免费在线SVG转PNG网站",
      },
      {
        title: "虫部落快搜",
        icon: "https://no.buging.cn/img/chongbuluo.png",
        link: "https://search.chongbuluo.com/",
        desc: "快搜！虫部落全网独家首发出品！为你聚合Google,百度,必应等国内外综合搜索和学术,资源,专业领域知识等垂直搜索。精准搜索,便捷交互！是你的网络搜索第一站！",
      },
      {
        title: "Photopea",
        icon: "https://no.buging.cn/img/photopea.png",
        link: "https://www.photopea.com/",
        desc: "免安装的网页版“ps完美替代者”——Photopea，走红国外！",
      },
      {
        title: "万能命令",
        icon: "https://no.buging.cn/img/wnrun.png",
        link: "https://wn.run/cn/",
        desc: "wn万能命令是一个在线工具效率平台，将各种高质量的在线工具按应用站点聚合起来，让你以方便快捷好记的方式寻找和使用各类在线工具。",
      },
    ],
  },
  {
    Category_id: "conference",
    title: "前端大会",
    category_icon: "icon-shequjiaozhengju",
    category_item: "conferenceItem",
    items: [
      {
        title: "JS 中国开发者大会",
        icon: "https://no.buging.cn/img/jsconfchina.png",
        link: "https://jsconfchina.com/",
        desc: "一场专注于JavaScript和Node.js技术的国际性大会",
      },
      {
        title: "中国 CSS 开发者大会",
        icon: "https://no.buging.cn/img/cssw3ctech.png",
        link: "https://css.w3ctech.com/",
        desc: "提高css开发姿势的大会。",
      },
      {
        title: "前端圈",
        icon: "https://no.buging.cn/img/fequan.png",
        link: "https://fequan.com/",
        desc: "打造专业的前端技术会议",
      },
      {
        title: "Vue.js开发者大会",
        icon: "https://no.buging.cn/img/vuew3ctech.png",
        link: "https://vue.w3ctech.com/",
        desc: "Vue.js开发者大会 中国站",
      },
    ],
  },
  {
    Category_id: "contentManagement",
    title: "内容管理",
    category_icon: "icon-navneirongguanli",
    category_item: "contentManagementItem",
    items: [
      {
        title: "WordPress",
        icon: "https://no.buging.cn/img/wordpress.png",
        link: "https://cn.wordpress.org/",
        desc: "WordPress是使用PHP语言开发的博客平台，用户可以在支持PHP和MySQL数据库的服务器上架设属于自己的网站。",
      },
      {
        title: "Hexo",
        icon: "https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg",
        link: "https://hexo.io/zh-cn/",
        desc: "快速、简洁且高效的博客框架",
      },
      {
        title: "GitHub Pages",
        icon: "https://no.buging.cn/img/GitHubPages.png",
        link: "https://pages.github.com/",
        desc: "Github Pages是Github免费提供给开发者的一款托管个人网站的产品。",
      },
      {
        title: "Jekyll",
        icon: "https://no.buging.cn/img/jekyll.png",
        link: "https://www.jekyll.com.cn/",
        desc: "将纯文本转化为静态网站和博客",
      },
      {
        title: "Wix",
        icon: "https://no.buging.cn/img/wix.png",
        link: "https://www.wix.com",
        desc: "免费的响应式商业化建站方案",
      },
      {
        title: "VuePress",
        icon: "https://www.vuepress.cn/hero.png",
        link: "https://www.vuepress.cn/",
        desc: "Vue 驱动的静态站点生成工具",
      },
      {
        title: "Docusaurus",
        icon: "https://docusaurus.io/img/icons/icon-144x144.png",
        link: "https://docusaurus.io/",
        desc: "Facebook出品的 简单的开源文档站点生成器",
      },
      {
        title: "docsify",
        icon: "https://docsify.js.org/_media/favicon.ico",
        link: "https://docsify.js.org/#/zh-cn/",
        desc: "一个神奇的文档站点生成器 简单轻巧",
      },
      {
        title: "Wiki js",
        icon: "https://wiki.js.org/favicon.ico",
        link: "https://wiki.js.org/",
        desc: "一个基于 NodeJS, Git 和 Markdown 的轻量级、现代化以及强大的 WIKI APP 生成工具",
      },
      {
        title: "GitBook",
        icon: "https://www.gitbook.com/public/g/icons/favicon.ico",
        link: "https://www.gitbook.com/",
        desc: "GitBook 是一个基于 Node.js 的命令行工具，可使用 Github/Git 和 Markdown 来制作精美的电子书",
      },
    ],
  },
  {
    Category_id: "someWebsite",
    title: "一些网站",
    category_icon: "icon-wangzhanguanli",
    category_item: "someWebsiteItem",
    items: [
      {
        title: "免费资源网络社区",
        icon: "https://free.com.tw/wp-content/uploads/2020/04/cropped-favicon-120x120.jpg",
        link: "https://free.com.tw/",
        desc: "一个以免费为主题的台湾网站、部落格，内容包含科技新知、免费软体、线上工具、图库素材、WordPress 架站及应用程式介绍教学",
      },
      {
        title: "吾爱破解",
        icon: "https://no.buging.cn/img/52pojie.png",
        link: "https://www.52pojie.cn/",
        desc: "吾爱破解论坛致力于软件安全与病毒分析的前沿，丰富的技术版块交相辉映，由无数热衷于软件加密解密及反病毒爱好者共同维护",
      },
      {
        title: "全能VIP视频在线解析",
        icon: "https://no.buging.cn/img/liumingyevideo.png",
        link: "http://tool.liumingye.cn/video/",
        desc: "优酷VIP解析,爱奇艺VIP解析,腾讯VIP解析,乐视VIP解析,芒果VIP解析,视频解析,全能VIP视频解析,视频在线解析",
      },
    ],
  },
  {
    Category_id: "environment",
    title: "作业环境",
    category_icon: "icon-aixin",
    category_item: "environmentItem",
    items: [
      {
        title: "VS Code",
        icon: "https://code.visualstudio.com/favicon.ico",
        link: "https://code.visualstudio.com/",
        desc: "这个不多说，个人开发编辑器",
      },
      {
        title: "Node.js",
        icon: "https://no.buging.cn/img/nodeapp.png",
        link: "http://nodejs.cn/download/",
        desc: "JavaScript 运行环境",
      },
      {
        title: "Git",
        icon: "https://git-scm.com/favicon.ico",
        link: "https://git-scm.com/",
        desc: "版本控制工具",
      },
      {
        title: "NVM",
        icon: "https://no.buging.cn/img/nvm.png",
        link: "https://github.com/nvm-sh/nvm",
        desc: "nvm (Node Version Manager) 是Nodejs版本管理器，可对不同的node版本快速进行切换。",
      },
      {
        title: "nvm-windows",
        icon: "https://no.buging.cn/img/nvm.png",
        link: "https://github.com/coreybutler/nvm-windows",
        desc: "nvm (Node Version Manager) 是Nodejs版本管理器，可对不同的node版本快速进行切换。",
      },
      {
        title: "Cmder",
        icon: "https://no.buging.cn/img/cmder.png",
        link: "https://cmder.app/",
        desc: "cmder是一个增强型命令工具，通过它可以使用Windows下的所有命令，可以使你像操作Linux一样操作Windows，是一个值得我们拥有的高逼格软件。",
      },
      {
        title: "马克鳗",
        icon: "https://no.buging.cn/img/markman.png",
        link: "http://www.getmarkman.com/",
        desc: "高效的设计稿标注、测量工具",
      },
      {
        title: "PxCook",
        icon: "https://no.buging.cn/img/pxcook.png",
        link: "https://www.fancynode.com.cn/pxcook",
        desc: "高效易用的自动标注工具, 生成前端代码",
      },
      {
        title: "Bandizip",
        icon: "https://no.buging.cn/img/bandizip.png",
        link: "http://www.bandizip.com/",
        desc: "个人最满意的压缩工具，没有之一",
      },
      {
        title: "Typora",
        icon: "https://no.buging.cn/img/typora.png",
        link: "https://www.typora.io/",
        desc: "一个适合新手的md编辑器，很好用",
      },
      {
        title: "ScreenToGif",
        icon: "https://www.screentogif.com/img/logo.d2151712.png",
        link: "https://www.screentogif.com/?l=zh_cn",
        desc: "非常好用的gif生成器",
      },
      {
        title: "Fences",
        icon: "https://www.stardock.com/products/fences/images/top/fences_icon_256.png",
        link: "https://www.stardock.com/products/fences/",
        desc: "最好的桌面整理软件",
      },
      {
        title: "Everything",
        icon: "https://no.buging.cn/img/Everything.png",
        link: "https://www.voidtools.com/zh-cn/",
        desc: "快速定位本地资源文件",
      },
      {
        title: "Listary",
        icon: "https://no.buging.cn/img/listary.png",
        link: "https://www.listary.com/",
        desc: "文件名定位/搜索辅助软件",
      },
      {
        title: "Snipaste",
        icon: "https://www.snipaste.com/img/logo.svg",
        link: "https://www.snipaste.com/",
        desc: "最好用的截图软件，没有之一",
      },
    ],
  },
];
