name: Deploy VIPTV site to Pages
on:  
  push:
  workflow_dispatch:
jobs:
  deploy-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false  

      - name:  Install and Build
        run: |   
          pnpm install
          pnpm build
    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_SECRET }}
          external_repository: viptv-work/viptv-work.github.io
          publish_dir: ./dist
          publish_branch: master
